IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'tracked_changes_nmped')
EXEC sys.sp_executesql N'CREATE SCHEMA [tracked_changes_nmped]'
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[LocalEducationAgencyTransportation]'))
CREATE TABLE [tracked_changes_nmped].[LocalEducationAgencyTransportation]
(
       OldCategoryDescriptor01TransportationCategoryDescriptorId [INT] NOT NULL,
       OldCategoryDescriptor01TransportationCategoryDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldCategoryDescriptor01TransportationCategoryDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldCategoryDescriptor02TransportationCategoryDescriptorId [INT] NOT NULL,
       OldCategoryDescriptor02TransportationCategoryDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldCategoryDescriptor02TransportationCategoryDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldLocalEducationAgencyId [INT] NOT NULL,
       OldTransportationSetCodeDescriptorId [INT] NOT NULL,
       OldTransportationSetCodeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTransportationSetCodeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewCategoryDescriptor01TransportationCategoryDescriptorId [INT] NULL,
       NewCategoryDescriptor01TransportationCategoryDescriptorNamespace [NVARCHAR](255) NULL,
       NewCategoryDescriptor01TransportationCategoryDescriptorCodeValue [NVARCHAR](50) NULL,
       NewCategoryDescriptor02TransportationCategoryDescriptorId [INT] NULL,
       NewCategoryDescriptor02TransportationCategoryDescriptorNamespace [NVARCHAR](255) NULL,
       NewCategoryDescriptor02TransportationCategoryDescriptorCodeValue [NVARCHAR](50) NULL,
       NewLocalEducationAgencyId [INT] NULL,
       NewTransportationSetCodeDescriptorId [INT] NULL,
       NewTransportationSetCodeDescriptorNamespace [NVARCHAR](255) NULL,
       NewTransportationSetCodeDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_LocalEducationAgencyTransportation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StaffDevelopment]'))
CREATE TABLE [tracked_changes_nmped].[StaffDevelopment]
(
       OldEducationOrganizationId [INT] NOT NULL,
       OldStaffUSI [INT] NOT NULL,
       OldStaffUniqueId [NVARCHAR](32) NOT NULL,
       OldStartDate [DATE] NOT NULL,
       NewEducationOrganizationId [INT] NULL,
       NewStaffUSI [INT] NULL,
       NewStaffUniqueId [NVARCHAR](32) NULL,
       NewStartDate [DATE] NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StaffDevelopment PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StaffEducationOrganizationVacancy]'))
CREATE TABLE [tracked_changes_nmped].[StaffEducationOrganizationVacancy]
(
       OldDataCollectionPeriodDescriptorId [INT] NOT NULL,
       OldDataCollectionPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldDataCollectionPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldLocalEducationAgencyId [INT] NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldVacancyGroupDescriptorId [INT] NOT NULL,
       OldVacancyGroupDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldVacancyGroupDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewDataCollectionPeriodDescriptorId [INT] NULL,
       NewDataCollectionPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewDataCollectionPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewLocalEducationAgencyId [INT] NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewVacancyGroupDescriptorId [INT] NULL,
       NewVacancyGroupDescriptorNamespace [NVARCHAR](255) NULL,
       NewVacancyGroupDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StaffEducationOrganizationVacancy PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StudentCTEProgramAssociationCredential]'))
CREATE TABLE [tracked_changes_nmped].[StudentCTEProgramAssociationCredential]
(
       OldBeginDate [DATE] NOT NULL,
       OldCredentialEarnedDate [DATE] NOT NULL,
       OldEducationOrganizationId [INT] NOT NULL,
       OldIndustryCredentialDescriptorId [INT] NOT NULL,
       OldIndustryCredentialDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldIndustryCredentialDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldProgramDeliveryMethodDescriptorId [INT] NOT NULL,
       OldProgramDeliveryMethodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramDeliveryMethodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldProgramEducationOrganizationId [INT] NOT NULL,
       OldProgramName [NVARCHAR](60) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewCredentialEarnedDate [DATE] NULL,
       NewEducationOrganizationId [INT] NULL,
       NewIndustryCredentialDescriptorId [INT] NULL,
       NewIndustryCredentialDescriptorNamespace [NVARCHAR](255) NULL,
       NewIndustryCredentialDescriptorCodeValue [NVARCHAR](50) NULL,
       NewProgramDeliveryMethodDescriptorId [INT] NULL,
       NewProgramDeliveryMethodDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramDeliveryMethodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewProgramEducationOrganizationId [INT] NULL,
       NewProgramName [NVARCHAR](60) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StudentCTEProgramAssociationCredential PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StudentEducationOrganizationAward]'))
CREATE TABLE [tracked_changes_nmped].[StudentEducationOrganizationAward]
(
       OldAwardDate [DATE] NOT NULL,
       OldEducationOrganizationId [INT] NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldStudentAwardLanguageDescriptorId [INT] NOT NULL,
       OldStudentAwardLanguageDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldStudentAwardLanguageDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStudentAwardTypeDescriptorId [INT] NOT NULL,
       OldStudentAwardTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldStudentAwardTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewAwardDate [DATE] NULL,
       NewEducationOrganizationId [INT] NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewStudentAwardLanguageDescriptorId [INT] NULL,
       NewStudentAwardLanguageDescriptorNamespace [NVARCHAR](255) NULL,
       NewStudentAwardLanguageDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStudentAwardTypeDescriptorId [INT] NULL,
       NewStudentAwardTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewStudentAwardTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StudentEducationOrganizationAward PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StudentSpecialEducationAssociationEvent]'))
CREATE TABLE [tracked_changes_nmped].[StudentSpecialEducationAssociationEvent]
(
       OldBeginDate [DATE] NOT NULL,
       OldEducationOrganizationId [INT] NOT NULL,
       OldEventDate [DATE] NOT NULL,
       OldProgramEducationOrganizationId [INT] NOT NULL,
       OldProgramName [NVARCHAR](60) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSpecialEducationEventTypeDescriptorId [INT] NOT NULL,
       OldSpecialEducationEventTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSpecialEducationEventTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewEducationOrganizationId [INT] NULL,
       NewEventDate [DATE] NULL,
       NewProgramEducationOrganizationId [INT] NULL,
       NewProgramName [NVARCHAR](60) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSpecialEducationEventTypeDescriptorId [INT] NULL,
       NewSpecialEducationEventTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewSpecialEducationEventTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StudentSpecialEducationAssociationEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[StudentSpecialEducationProgramAssociationIEPDates]'))
CREATE TABLE [tracked_changes_nmped].[StudentSpecialEducationProgramAssociationIEPDates]
(
       OldBeginDate [DATE] NOT NULL,
       OldEducationOrganizationId [INT] NOT NULL,
       OldIEPBeginDate [DATE] NOT NULL,
       OldProgramEducationOrganizationId [INT] NOT NULL,
       OldProgramName [NVARCHAR](60) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewEducationOrganizationId [INT] NULL,
       NewIEPBeginDate [DATE] NULL,
       NewProgramEducationOrganizationId [INT] NULL,
       NewProgramName [NVARCHAR](60) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StudentSpecialEducationProgramAssociationIEPDates PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[VehicleMileage]'))
CREATE TABLE [tracked_changes_nmped].[VehicleMileage]
(
       OldLocalEducationAgencyId [INT] NOT NULL,
       OldMileageTypeDescriptorId [INT] NOT NULL,
       OldMileageTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldMileageTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldReportingDate [DATE] NOT NULL,
       OldRoadTypeDescriptorId [INT] NOT NULL,
       OldRoadTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldRoadTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldVehicleId [NVARCHAR](255) NOT NULL,
       OldVehicleRouteDescriptorId [INT] NOT NULL,
       OldVehicleRouteDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldVehicleRouteDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewLocalEducationAgencyId [INT] NULL,
       NewMileageTypeDescriptorId [INT] NULL,
       NewMileageTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewMileageTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewReportingDate [DATE] NULL,
       NewRoadTypeDescriptorId [INT] NULL,
       NewRoadTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewRoadTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewVehicleId [NVARCHAR](255) NULL,
       NewVehicleRouteDescriptorId [INT] NULL,
       NewVehicleRouteDescriptorNamespace [NVARCHAR](255) NULL,
       NewVehicleRouteDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_VehicleMileage PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_nmped].[VehicleSnapshot]'))
CREATE TABLE [tracked_changes_nmped].[VehicleSnapshot]
(
       OldLocalEducationAgencyId [INT] NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldVehicleId [NVARCHAR](255) NOT NULL,
       OldVehicleIdentificationNumber [NVARCHAR](21) NOT NULL,
       NewLocalEducationAgencyId [INT] NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewVehicleId [NVARCHAR](255) NULL,
       NewVehicleIdentificationNumber [NVARCHAR](21) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_VehicleSnapshot PRIMARY KEY CLUSTERED (ChangeVersion)
)
